### ISSUE TITLE
MACD Histogram values incorrect

### ISSUE THREAD

**Issue by RetributionByRevenue** [kaelzhang/stock-pandas#12]
Your macd histogram does not output the correct values. I will attempt to fix your macd histogram, i cannot make any promises

**Comment by kaelzhang** [comment]
Could you provide more details, either about
- the calculation formula [here](https://github.com/kaelzhang/stock-pandas/blob/0.25.3/stock_pandas/commands/trend_following.py#L113)
- or the test cases [here](https://github.com/kaelzhang/stock-pandas/blob/0.25.3/test/test_commands.py#L92) -> seems that I really did not provide enough test cases

**Comment by kaelzhang** [comment]
Usually, there are two choices of the histogram times upon the difference of macd and macd signal, `1` or `2` ([here](https://github.com/kaelzhang/stock-pandas/blob/0.25.3/stock_pandas/commands/trend_following.py#L118)) which, however, might not affect the trading decision.

**Comment by RetributionByRevenue** [comment]
sorry after a closer investigation, i believed  have made a mistake. there isn't a bug

**Comment by kaelzhang** [comment]
@RetributionByRevenue 

[volas](https://github.com/kaelzhang/volas) will be the successor to `stock-pandas`, completely rebuilt using Rust, with a pandas-compatible API and full support for stock indicators aligned with TA-Lib.

`volas`'s stock indicator calculation performance is up to 140x faster than `pandas`, tens of times faster than `stock-pandas`, and its overall performance even surpasses TA-Lib on 146 of 158 indicators
