### ISSUE TITLE
Add: PROC

### ISSUE THREAD

**Issue by iaadefila** [kaelzhang/stock-pandas#13]
#### Why this feature is better to be included in stock-pandas? Please describe the scenario
Through a simple calculation, the inclusion of Price Rate of Change (PROC) will further enhance the applicability of the library as a one-stop for stock analysis.

#### Provide 1-2 code examples that the usage of the new feature:

```py

```

**Comment by kaelzhang** [comment]
ROC (or PROC) is equivalent to 

```py
stock['change:(column:close),20']
```

Check https://github.com/kaelzhang/stock-pandas#change for details

**Comment by kaelzhang** [comment]
@iaadefila 

[volas](https://github.com/kaelzhang/volas) will be the successor to `stock-pandas`, completely rebuilt using Rust, with a pandas-compatible API and full support for stock indicators aligned with TA-Lib.

`volas`'s stock indicator calculation performance is up to 140x faster than `pandas`, tens of times faster than `stock-pandas`, and its overall performance even surpasses TA-Lib on 146 of 158 indicators
