### ISSUE TITLE
MACD calculation not working with pandas > 1.1.5

### ISSUE THREAD

**Issue by avocadochicken** [kaelzhang/stock-pandas#14]
stock['macd'] does not work anymore.

Pandas API changed in file 'pandas/_libs/window/aggregations.pyx'. See: https://github.com/pandas-dev/pandas/commit/e0547d1be93fd71af5e947491a9466fdaf6ebefb#diff-a7e54d30487a86e702ec9fcbf41c09293d0f4ad0aaba24caee3a5dde24d8ff01

def ewma(float64_t[:] vals, float64_t com, bint adjust, bint ignore_na, int minp):
-> def ewma(float64_t[:] vals, int64_t[:] start, int64_t[:] end, int minp, float64_t com, bint adjust, bint ignore_na):

'stock_pandas/math/ma.py' line 27 must be adjusted.

**Comment by kaelzhang** [comment]
It was really bad to use internal pandas methods which has been changed for several times among the recent versions.

I'll check this.

**Comment by kaelzhang** [comment]
Working in progress

- [x] fixes import error
- [ ] fixes travis-ci

**Comment by kaelzhang** [comment]
For now, `stock-pandas` does not rely on `cython` modules of `pandas`, but it requires additional dependencies to be installed first. 

Check [here](https://github.com/kaelzhang/stock-pandas#install)

Feel free to reopen this issue or create new issue if any problems.

**Comment by kaelzhang** [comment]
@avocadochicken 

[volas](https://github.com/kaelzhang/volas) will be the successor to `stock-pandas`, completely rebuilt using Rust, with a pandas-compatible API and full support for stock indicators aligned with TA-Lib.

`volas`'s stock indicator calculation performance is up to 140x faster than `pandas`, tens of times faster than `stock-pandas`, and its overall performance even surpasses TA-Lib on 146 of 158 indicators
