### ISSUE TITLE
Installation in "requirements.txt" only environments

### ISSUE THREAD

**Issue by k1mbl3** [kaelzhang/stock-pandas#17]
There are environments were you can only install deps writing it on requirements.txt (google cloud funtions, google app engine, heroku etc), and since the only way to install stock-pandas is to have numpy already installed, it raises this error when i try

Step 8/13 : RUN pip3 install -r requirements.txt
 ---> Running in 6a96da2c5cf5
Collecting numpy==1.20.1
  Downloading numpy-1.20.1-cp38-cp38-manylinux2010_x86_64.whl (15.4 MB)
Collecting pandas==1.2.2
  Downloading pandas-1.2.2-cp38-cp38-manylinux1_x86_64.whl (9.7 MB)
Collecting python-dateutil==2.8.1
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytz==2021.1
  Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
Collecting six==1.15.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting stock-pandas==0.29.0
  Downloading stock-pandas-0.29.0.tar.gz (134 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zxl3pouu/stock-pandas/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zxl3pouu/stock-pandas/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-zxl3pouu/stock-pandas/pip-egg-info
         cwd: /tmp/pip-install-zxl3pouu/stock-pandas/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zxl3pouu/stock-pandas/setup.py", line 10, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c pip3 install -r requirements.txt' returned a non-zero code: 1

**Comment by kaelzhang** [comment]
Yes, for now, we need numpy installed first as I mentioned in README.md

Publishing built binaries for all platforms takes too much time which I don't have.

For google app engines or keroku, you could define your custom `app.yaml` or something and custom `Dockerfile` to manage the building process.

For example:

```dockerfile
# Dockerfile

# Tensorflow 2 do not support python 3.9 for now, so use python 3.8 is a common practice.
FROM python:3.8

RUN pip3 install numpy

COPY requirements.txt ./
RUN pip3 install -r requirements.txt

...
```

**Comment by k1mbl3** [comment]
In Google cloud functions you can't use a custom docker file, so I will move the project to Google cloud run. Thanks.

**Comment by kaelzhang** [comment]
Since `1.2.7`, it no longer requires installing numpy first

**Comment by kaelzhang** [comment]
@k1mbl3 

[volas](https://github.com/kaelzhang/volas) will be the successor to `stock-pandas`, completely rebuilt using Rust, with a pandas-compatible API and full support for stock indicators aligned with TA-Lib.

`volas`'s stock indicator calculation performance is up to 140x faster than `pandas`, tens of times faster than `stock-pandas`, and its overall performance even surpasses TA-Lib on 146 of 158 indicators
