### ISSUE TITLE
dynamic set move average window size

### ISSUE THREAD

**Issue by andrewpedia** [kaelzhang/stock-pandas#24]
if  I can dynamic set move average window size , it will be convinient to do backtest

**Comment by kaelzhang** [comment]
Can you provide a concrete use case?

```py
stock['ma:10']  // a 10-period moving average
stock['ma:20'] // a 20-period moving average
```

**Comment by kaelzhang** [comment]
/close for now

Be free to reopen the issue if necessary

**Comment by kaelzhang** [comment]
@andrewpedia 

[volas](https://github.com/kaelzhang/volas) will be the successor to `stock-pandas`, completely rebuilt using Rust, with a pandas-compatible API and full support for stock indicators aligned with TA-Lib.

`volas`'s stock indicator calculation performance is up to 140x faster than `pandas`, tens of times faster than `stock-pandas`, and its overall performance even surpasses TA-Lib on 146 of 158 indicators
