### ISSUE TITLE
import error 

### ISSUE THREAD

**Issue by alfredaita** [kaelzhang/stock-pandas#4]
No module named 'pandas._libs.window.aggregations'

**Comment by kaelzhang** [comment]
Which version of `pandas` do you use?

**Comment by kaelzhang** [comment]
stock-pandas requires pandas >= 1.0.0, I've just update the requirements.txt.

stock-pandas uses some CPython module of pandas for calculation to improve performance

**Comment by kaelzhang** [comment]
@alfredaita Just figure out that you are the one in the data science industry. I'd like to provide you better support for this project, and I will reply to every issue within 24 hours, because recently I will devote more time on stock-pandas than other open source projects.

**Comment by kaelzhang** [comment]
close for now.

**Comment by kaelzhang** [comment]
[volas](https://github.com/kaelzhang/volas) will be the successor to `stock-pandas`, completely rebuilt using Rust, with a pandas-compatible API. 

`volas`'s stock indicator calculation performance is up to 140x faster than pandas, and its overall performance even surpasses TA-Lib on 146 of 158 indicators
